version: '3.8'
services:
  app:
    container_name: tms_app_compose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORTS}
    volumes:
      - /data
      - /var/log/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: ${DB_IMAGE}
    container_name: tms_db_compose
    ports:
      - ${DB_PORTS}
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}