server:
  port: ${SERVER_PORT}

spring:
  application:
    name: TaskManagementSystem
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/master.yaml

jwt:
  expiration: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET_KEY}
logging:
  level:
    org.hibernate:
      sql: debug
      type.descriptor.sql: trace
    org.springframework.security: debug