server:
  port: 8089

spring:
  application:
    name: TaskManagementSystem
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect